### ISSUE TITLE
Blocks google.com and www.google.com

### ISSUE THREAD

**Issue by picklejw** [slyfox1186/pihole.youtube.blocklist#3]
This block regex blocks google landing for search:
^[\w\-\.]*?google(?:adservices|apis|syndication|usercontent)?\.com$

Is there a step I am missing besides installing and adding whitelist?
Also... what URLs are these intending to block. I would like to help but don't want to break the intent this block was used for.

**Comment by slyfox1186** [comment]
Some of the issues with complicated regex patterns as you can see in the example you pointed out are that there are going to be casualties AKA false positives and negatives. The goal with these types of extreme regex patterns is to have 95% of matches be what you would consider a success if you were made aware of the results and understood them all, and only 5% or fewer failures. That is a ratio that would make the regex pattern well worth its salt.

To solve this issue with the examples you gave you can for the moment simply create an exact whitelist for www.google.com and google.com and the issue will be resolved for those domains as they will be overridden.

And finally, to answer your main question about what is the overall purpose..... these are well-known google ad domains, and since google uses many different rotational domains that serve up metadata and other DNS information this helps make the blanket of coverage greater which hopefully will lead to an overall decrease in the number of ads Google is able to serve you when viewing youtube videos. 

In the meantime, I am working on regex whitelist and other exact whitelists to coincide with these regex blacklists. Stay tuned.
